---
title: "Causality in Machine Learning: Class projects"
author: "Robert Ness"
output: pdf_document
header-includes:
   - \usepackage[table,xcdraw]{xcolor}
urlcolor: blue
---

This course focuses on the application of causal inference theory in generative machine learning.  The course project requires you to implement a cutting-edge causal machine learning workflow.

You are implementing your project in groups of 2-3 students.  The final deliverable is a Github repository that includes notebooks with code and description, and a presentation of your results to the class.

Please choose one of the following projects.


## Agent models for causal scene generation

In this course we have been learning to reflect on a data generating process and represent it with a causal model.

Flickr8 is a [dataset](https://github.com/jbrownlee/Datasets/releases/) used to train deep learning models that generate captions like the following;

    A girl going into a wooden building .
    A little girl climbing into a wooden playhouse .
    A little girl climbing the stairs to her playhouse .
    A little girl in a pink dress going into a wooden cabin .
    A black dog and a spotted dog are fighting
    A black dog and a tri-colored dog playing with each other on the road .
    A black dog and a white dog with brown spots are staring at each other in the street .

However, if we take a [vision-as-inverse-graphics](https://ps.is.tuebingen.mpg.de/research_fields/inverse-graphics) view of computer vision, we could think of captions as a natural language representation of the data generating process that generated tge accompanying image.

Your job in this project is to take these natural language descriptions and turn them into the basic ingrediates of a probabilistic programs.

### Deliverables

Collect a set of 100 captions, and create a set of object classes in Python. E.g., "A black dog" could be of a class "Animal" with a color attribute "black". Methods on these classes will handle actions like "staring" and "fighting."  Once these abstractions are created, use them to create a probabilistic program that describes the images.  That probabilistic program will include an EXTREMELY simple procedural 2D image generator that generates primitive pictures of the images described by the program.


## Deep causal variational inference

This project is ideal for students interested in deep causal generative model.

In this project, you will be provided code that does supervised learning of a variational autoencoder on Deepmind's [dSprites](https://github.com/deepmind/dsprites-dataset) dataset.

dSprites is a dataset of sprites, which are 2D shapes procedurally generated from 5 ground truth independent "factors." These factors are color, shape, scale, rotation, x and y positions of a sprite.

All possible combinations of these variables are present exactly once, generating N = 737280 total images.

Factors and their values:

* Shape: 3 values {square, ellipse, heart}
* Scale: 6 values linearly spaced in (0.5, 1)
* Orientation: 40 values in (0, 2$\pi$)
* Position X: 32 values in (0, 1)
* Position Y: 32 values in (0, 1)

### Deliverables

In this project, you will refactor the provided program such that there is a causal relationship between the above variables.  Once retrained, you will be able to apply interventions to elements of this program and have that generate a new image that reflects that intervention.  The causal structure will be provided.


## Counterfactual policy evaluation with Open AI gym

This project is ideal for students who are interested in reinforcement learning.

In this project, you will take an environment from [OpenAI gym](https://gym.openai.com/) and demonstrate a counterfactual evaluation use case.

### Deliverables

You will be provided with working code implementing a modified FrozenLake environment in OpenAI.  If you choose this project, you will choose from one of the following goals.

* Extend the current model to a different OpenAI environment
* Implement a traditional RL algorithm and compare it to a similar algorithm that incorporates causal elements.
* Modify the model such that you can apply counterfactual reasoning on logged data.

[Counterfactual Off-Policy Evaluation with Gumbel-Max Structural Causal Models](https://arxiv.org/abs/1905.05824)


## Causal data science analysis

In this project we will do a typical data science analysis, while applying causal modeling principles.  We will work with [  Airbnb](http://insideairbnb.com/get-the-data.html) data and related housing datasets. The goal of the analysis is to build a causal generative model that allows you to identify the causal effect of various factors on Airbnb income relative to the market price of the unit.


## DIY causal modeling language

In this project, you build your own prototype causal modeling language using Haskell, Scala, Scheme, R, or whatever you prefer.  This project is suitable for students already familiar with design and implementation of programming languages.  Here are some reference readings:

[Practical Probabilistic Programming with Monads](http://mlg.eng.cam.ac.uk/pub/pdf/SciGhaGor15.pdf)

[Write your own general-purpose monadic probabilistic programming language from scratch in 50 lines of (Scala) code](https://darrenjw.wordpress.com/2019/08/07/write-your-own-general-purpose-monadic-probabilistic-programming-language-from-scratch-in-50-lines-of-scala-code/)

[A Language for Counterfactual Generative Models](http://www.zenna.org/publications/causal.pdf)

If interested, ask the professor for more relevant readings.
